#!/bin/bash
cat docker/k8s/* | envsubst | kubectl apply -n $KUBE_NAMESPACE -f -

echo "Waiting for deployment app...."
kubectl rollout status -n "$KUBE_NAMESPACE" -w "deployment/$CI_ENVIRONMENT_SLUG"

echo "Waiting for deployment database...."
kubectl rollout status -n "$KUBE_NAMESPACE" -w "deployment/agid-db"

echo "Application is accessible at: ${CI_ENVIRONMENT_URL}"
echo ""
