#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DEPLOY_ROOT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
export DEPLOY_ROOT_DIR

# shellcheck disable=SC1091
source "$DEPLOY_ROOT_DIR/src/common.bash"

# shellcheck disable=SC1091
source "$DEPLOY_ROOT_DIR/src/functions.bash"

create_kubeconfig

echo "Removing all pods..."
kubectl delete all -l "branch=${CI_BUILD_REF_SLUG},app=${CI_ENVIRONMENT_SLUG}" -n "${KUBE_NAMESPACE}"
