#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DEPLOY_ROOT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
export DEPLOY_ROOT_DIR
source "$DEPLOY_ROOT_DIR/src/common.bash"
export NODE_SELECTOR=${NODE_SELECTOR:-cloud.google.com/gke-nodepool=gitlab-ci}

create_kubeconfig

helm-init() {
  kubectl create ns $KUBE_NAMESPACE || true
  helm init --node-selectors="${NODE_SELECTOR}" --tiller-namespace ${KUBE_NAMESPACE}
  kubectl rollout status -w deployment/tiller-deploy --namespace=${KUBE_NAMESPACE}
  kubectl scale deployment tiller-deploy --replicas=1 --namespace=${KUBE_NAMESPACE}
  helm repo add sparkfabrik https://storage.googleapis.com/spark-helm-charts/
}

helm-init
